# Generated by Django 5.1.5 on 2025-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_dips_pull_ups_delete_score_dips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dips',
            name='rank',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='pull_ups',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
